[tool.isort]
# Setting compatible with black. See https://black.readthedocs.io/en/stable/compatible_configs.html
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 120

[tool.black]
line-length = 120
target-version = ['py38']
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.poetry]
name = "todoist-habitica-sync"
version = "1.0.0"
description = "One way synchronisation from Todoist to Habitica."
authors = ["Radek Lát <radek.lat@gmail.com>"]
license = "MIT License"

[tool.poetry.dependencies]
python = "^3.8"
todoist-python = "^8.0"
tinydb = "^3.14"
ujson = "^1.35"
dotmap = "^1.3"
requests = "^2.22"
python-dateutil = "^2.8"
pydantic = {version = "^1.8", extras = ["dotenv"]}

[tool.poetry.dev-dependencies]
coverage = "^5.5"
pylint = "^2.7.2"
mypy = "^0.812"
pytest = "^6.2.2"
pytest-cov = "^2.11.1"
pre-commit = "^2.11.1"
black = "^20.8b1"
invoke = "^1.5.0"
termcolor = "^1.1.0"
poetry = "^1.1.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
